import Foundation
import SandvaultCore

/// Generates the pf rules for the anchor `AppPaths.pfAnchor` from the network policy.
///
/// Every rule matches the sandbox user's sockets with `user <uid>` (pf knows the owner for TCP and UDP only).
/// Translation rules come first, as pf requires inside an anchor. A packet re-routed with `route-to (lo0 ...)` is
/// evaluated again as "out on lo0" with its original, non-loopback destination; therefore the localhost policy
/// targets loopback destinations only and the re-routed flow gets its own pass rule.
public enum PFAnchorGenerator {
    static let loopback = "{ 127.0.0.0/8 ::1 }"
    static let tcpUDP = "proto { tcp udp }"

    /// The anchor text, or `nil` for `FirewallMode.off` (the anchor is flushed).
    public static func rules(for state: AppliedState, uid: UInt32) throws -> String? {
        try SandboxAccount.validate(uid: uid)
        let policy = state.network
        guard policy.mode != .off else { return nil }
        let user = "user \(uid)"
        let ports = policy.ports
        for port in ports.all where port == 0 { throw SandvaultError.invalidInput("netd port 0 in the network policy") }
        if state.dynamicLocalPorts.contains(0) { throw SandvaultError.invalidInput("dynamic local port 0") }

        var groups: [[String]] = [[
            "# Sandvault Config anchor \(AppPaths.pfAnchor), generated by svctl-helper. svctl firewall apply rewrites it.",
            "# Mode \(policy.mode.cliName). Rules match the sandbox user's sockets (\(user)); pf knows owners of TCP and UDP only.",
        ]]

        switch policy.mode {
        case .off:
            return nil

        case .blocked:
            groups.append([
                "# Blocked: every TCP and UDP packet of the sandbox user is refused, in both directions, on every interface.",
                "block return log quick \(tcpUDP) from any to any \(user)",
            ])

        case .open, .watch:
            if policy.mode == .watch {
                groups.append(translation(ports))
                groups.append(reroute(user))
                groups.append([
                    "# Watch: IPv6 web and DNS cannot be re-routed; refuse them so clients fall back to IPv4 through netd.",
                    "block return out log quick inet6 proto tcp from any to ! ::1 port { 53 80 443 } \(user)",
                    "block return out log quick inet6 proto udp from any to ! ::1 port 53 \(user)",
                ])
            }
            groups.append(netd(ports, user))
            groups.append(contentsOf: try exceptions(policy.portExceptions, user))
            if policy.blockLAN {
                groups.append([
                    "# LAN guard: no direct traffic to private, link-local, CGNAT and multicast networks.",
                    "block return out log quick \(tcpUDP) from any to \(list(PrivateNetworks.lan.map(format))) \(user)",
                ])
            }
            groups.append(localhost(policy, state.dynamicLocalPorts, user))
            groups.append([
                "# Everything else is allowed in \(policy.mode.cliName) mode.",
                "pass out quick \(tcpUDP) from any to any \(user) keep state",
            ])

        case .proxyOnly:
            groups.append(translation(ports))
            groups.append(reroute(user))
            groups.append(netd(ports, user))
            groups.append(contentsOf: try exceptions(policy.portExceptions, user))
            groups.append(localhost(policy, state.dynamicLocalPorts, user))
            groups.append([
                "# Everything else of the sandbox user is refused (IPv4 and IPv6).",
                "block return out log quick \(tcpUDP) from any to any \(user)",
            ])
        }
        return groups.map { $0.joined(separator: "\n") }.joined(separator: "\n\n") + "\n"
    }

    // MARK: - Groups

    static func translation(_ ports: ProxyPorts) -> [String] {
        [
            "# Translation: flows re-routed to lo0 below still carry their original destination; hand them to netd.",
            "# Note: this also catches any local user's lo0 packets to this Mac's own non-loopback addresses on these ports.",
            "rdr pass on lo0 inet proto tcp from any to ! 127.0.0.0/8 port 80 -> 127.0.0.1 port \(ports.transparentHTTP)",
            "rdr pass on lo0 inet proto tcp from any to ! 127.0.0.0/8 port 443 -> 127.0.0.1 port \(ports.transparentTLS)",
            "rdr pass on lo0 inet \(tcpUDP) from any to ! 127.0.0.0/8 port 53 -> 127.0.0.1 port \(ports.dns)",
        ]
    }

    static func reroute(_ user: String) -> [String] {
        [
            "# Re-route HTTP, HTTPS and DNS of the sandbox user to lo0 (IPv4; IPv6 is refused below and clients fall back).",
            "pass out quick on ! lo0 route-to (lo0 127.0.0.1) inet proto tcp from any to any port { 53 80 443 } \(user) keep state",
            "pass out quick on ! lo0 route-to (lo0 127.0.0.1) inet proto udp from any to any port 53 \(user) keep state",
            "# A re-routed packet is evaluated again as \"out on lo0\" with its original destination: let it through.",
            "pass out quick on lo0 inet proto tcp from any to ! 127.0.0.0/8 port { 53 80 443 } \(user) keep state",
            "pass out quick on lo0 inet proto udp from any to ! 127.0.0.0/8 port 53 \(user) keep state",
        ]
    }

    static func netd(_ ports: ProxyPorts, _ user: String) -> [String] {
        [
            "# netd on loopback: explicit proxy, transparent HTTP and TLS listeners, DNS forwarder.",
            "pass out quick \(tcpUDP) from any to 127.0.0.1 port \(list(Set(ports.all).sorted().map(String.init))) \(user) keep state",
        ]
    }

    static func exceptions(_ exceptions: [PortException], _ user: String) throws -> [[String]] {
        guard !exceptions.isEmpty else { return [] }
        var lines = ["# Exceptions (svctl firewall except): explicit grants, evaluated before the guards below."]
        for exception in exceptions {
            let note = SBPLGenerator.sanitizeNote(exception.note ?? "")
            lines.append("# exception \(exception.id.uuidString.lowercased())" + (note.isEmpty ? "" : ": \(note)"))
            lines.append("pass out quick proto \(exception.proto.rawValue) from any to \(try destination(exception))\(try portClause(exception)) \(user) keep state")
        }
        return [lines]
    }

    static func localhost(_ policy: NetworkPolicy, _ dynamicPorts: [UInt16], _ user: String) -> [String] {
        let inbound = "pass in quick on lo0 \(tcpUDP) from any to any \(user) keep state"
        let refuse = "block return out log quick \(tcpUDP) from any to \(loopback) \(user)"
        let explain = [
            "# Only loopback destinations are refused, so flows re-routed to lo0 keep passing.",
            "# Connections the host opens to the sandbox's listeners keep state, so their replies are not refused.",
        ]
        switch policy.localhost {
        case .allowAll:
            return ["# Localhost (allow-all): every loopback port is reachable.", inbound,
                    "pass out quick \(tcpUDP) from any to \(loopback) \(user) keep state"]
        case .blockAll:
            return ["# Localhost (block-all): on loopback only netd (above) is reachable."] + explain + [inbound, refuse]
        case .sandboxAndHelpers:
            let extra = Set(dynamicPorts).subtracting(policy.ports.all).sorted()
            var lines = ["# Localhost (sandbox-and-helpers): netd plus the sandbox's own listeners and sv's host helpers."]
            lines += explain + [inbound]
            if !extra.isEmpty {
                lines.append("pass out quick \(tcpUDP) from any to \(loopback) port \(list(extra.map(String.init))) \(user) keep state")
            }
            lines.append(refuse)
            return lines
        }
    }

    // MARK: - Formatting and validation

    /// `any`, or the canonical form of a CIDR / single address. Raw input never reaches the rule text.
    static func destination(_ exception: PortException) throws -> String {
        if exception.destination.lowercased() == "any" { return "any" }
        guard let range = AddressRange(exception.destination) else {
            throw SandvaultError.invalidInput("exception destination must be an address, a CIDR or 'any': \(SBPLGenerator.printable(exception.destination))")
        }
        return format(range)
    }

    static func portClause(_ exception: PortException) throws -> String {
        guard let port = exception.port else { return "" }
        guard port != 0 else { throw SandvaultError.invalidInput("exception port 0") }
        return " port \(port)"
    }

    static func list(_ items: [String]) -> String {
        items.count == 1 ? items[0] : "{ " + items.joined(separator: " ") + " }"
    }

    /// Address with the longest zero run of IPv6 compressed; host ranges without the prefix length.
    static func format(_ range: AddressRange) -> String {
        let address: String
        switch range.family {
        case .ipv4:
            address = range.bytes.map(String.init).joined(separator: ".")
        case .ipv6:
            let groups = stride(from: 0, to: 16, by: 2).map { UInt16(range.bytes[$0]) << 8 | UInt16(range.bytes[$0 + 1]) }
            var best = (start: 0, length: 0), runStart = -1
            for (index, group) in groups.enumerated() {
                if group != 0 { runStart = -1; continue }
                if runStart < 0 { runStart = index }
                if index - runStart + 1 > best.length { best = (runStart, index - runStart + 1) }
            }
            let hex = groups.map { String($0, radix: 16) }
            address = best.length >= 2
                ? hex[..<best.start].joined(separator: ":") + "::" + hex[(best.start + best.length)...].joined(separator: ":")
                : hex.joined(separator: ":")
        }
        let hostLength = range.family == .ipv4 ? 32 : 128
        return range.prefixLength == hostLength ? address : "\(address)/\(range.prefixLength)"
    }
}

extension FirewallMode {
    /// Name used by the CLI and in generated text.
    public var cliName: String {
        switch self {
        case .off: "off"
        case .open: "open"
        case .watch: "watch"
        case .proxyOnly: "proxy-only"
        case .blocked: "blocked"
        }
    }
}

extension LocalhostPolicy {
    public var cliName: String {
        switch self {
        case .sandboxAndHelpers: "sandbox-and-helpers"
        case .allowAll: "allow-all"
        case .blockAll: "block-all"
        }
    }
}
