import Foundation
import SandvaultCore

/// Generates the managed block that is appended to sv's sandbox profile.
///
/// sv's profile ends with `(allow default)` plus denials; SBPL is last-match-wins, so rules in the block override
/// sv's. Order inside the block: hardened preset (if selected), then file, mach and exec rules in config order,
/// so a user rule can override the preset. Validation is the security boundary: anything that could break out of
/// a string literal or a comment is rejected, never repaired.
public enum SBPLGenerator {
    public static let maxPathLength = 1024
    public static let maxNoteLength = 120

    static let header = ";; Generated by Sandvault Config (svctl rules). Last match wins: these rules override sv's above."

    /// The block body for `settings`, or `nil` when there is nothing to add (standard preset, no rules).
    public static func block(for settings: SandboxSettings) throws -> String? {
        var lines: [String] = []
        if settings.preset == .hardened {
            lines.append(";; preset hardened (opt-in, conservative; verify on a real Mac)")
            for entry in HardenedPreset.entries {
                lines.append(";; hardened: \(entry.reason)")
                lines.append(try expression(for: entry))
            }
        }
        for rule in settings.fileRules {
            lines.append(comment(id: rule.id, note: rule.note))
            lines.append(try expression(for: rule))
        }
        for rule in settings.machRules {
            lines.append(comment(id: rule.id, note: rule.note))
            lines.append(try expression(for: rule))
        }
        for rule in settings.execRules {
            lines.append(comment(id: rule.id, note: rule.note))
            lines.append(try expression(for: rule))
        }
        guard !lines.isEmpty else { return nil }
        let body = ([header] + lines).joined(separator: "\n")
        // A path that spells a marker would make ManagedBlock cut the block in the wrong place.
        let markers = [ManagedBlock.sandboxProfile.begin, ManagedBlock.sandboxProfile.end]
        if markers.contains(where: { body.contains($0) }) {
            throw SandvaultError.invalidInput("a rule contains the managed block marker text")
        }
        return body
    }

    public static func expression(for rule: FileRule) throws -> String {
        let operations: String
        switch rule.access {
        case .read: operations = "file-read*"
        case .write: operations = "file-write*"
        case .readWrite: operations = "file-read* file-write*"
        }
        return "(\(rule.effect.rawValue) \(operations) (\(rule.match.rawValue) \(try pathLiteral(rule.path))))"
    }

    public static func expression(for rule: MachRule) throws -> String {
        "(\(rule.effect.rawValue) mach-lookup (global-name \(try machLiteral(rule.name))))"
    }

    public static func expression(for rule: ExecRule) throws -> String {
        "(\(rule.effect.rawValue) process-exec (literal \(try pathLiteral(rule.path))))"
    }

    static func expression(for entry: PresetEntry) throws -> String {
        switch entry.kind {
        case .exec(let path): try expression(for: ExecRule(path: path, effect: .deny))
        case .mach(let name): try expression(for: MachRule(name: name, effect: .deny))
        }
    }

    // MARK: - Validation

    /// Checks an absolute path for use in an SBPL filter: no control or format characters, no line breaks,
    /// no empty, `.` or `..` components, at most `maxPathLength` bytes.
    public static func validatePath(_ path: String) throws {
        guard path.hasPrefix("/") else { throw SandvaultError.invalidInput("path must be absolute: \(printable(path))") }
        guard path.utf8.count <= maxPathLength else {
            throw SandvaultError.invalidInput("path longer than \(maxPathLength) bytes: \(printable(path))")
        }
        for scalar in path.unicodeScalars where isForbidden(scalar) {
            throw SandvaultError.invalidInput("path contains a control or line-break character: \(printable(path))")
        }
        guard path != "/" else { return }
        for component in path.dropFirst().split(separator: "/", omittingEmptySubsequences: false) {
            if component.isEmpty || component == "." || component == ".." {
                throw SandvaultError.invalidInput("path must not contain empty, '.' or '..' components: \(printable(path))")
            }
        }
    }

    /// Mach service names: `^[A-Za-z0-9._-]{1,255}$`.
    public static func validateMachName(_ name: String) throws {
        let allowed = name.utf8.allSatisfy { byte in
            (byte >= 0x30 && byte <= 0x39) || (byte >= 0x41 && byte <= 0x5A) || (byte >= 0x61 && byte <= 0x7A)
                || byte == 0x2E || byte == 0x5F || byte == 0x2D
        }
        guard allowed, (1...255).contains(name.utf8.count) else {
            throw SandvaultError.invalidInput("mach service name must match [A-Za-z0-9._-]{1,255}: \(printable(name))")
        }
    }

    static func pathLiteral(_ path: String) throws -> String {
        try validatePath(path)
        return quote(path)
    }

    static func machLiteral(_ name: String) throws -> String {
        try validateMachName(name)
        return quote(name)
    }

    /// SBPL string literal; backslash and double quote are the only escapes needed once validation passed.
    static func quote(_ text: String) -> String {
        "\"" + text.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"") + "\""
    }

    static func comment(id: UUID, note: String?) -> String {
        let cleaned = note.map(sanitizeNote) ?? ""
        return ";; rule \(id.uuidString.lowercased())" + (cleaned.isEmpty ? "" : ": \(cleaned)")
    }

    /// A note reduced to letters, digits, spaces and plain ASCII punctuation on one line (also used for pf comments).
    public static func sanitizeNote(_ note: String) -> String {
        let punctuation = Set(".,:;_-+/()[]@#&=?!%*'\"~")
        var result = ""
        var lastWasSpace = true
        for character in note {
            let keep = character.isLetter || character.isNumber || punctuation.contains(character)
            if keep && character.unicodeScalars.allSatisfy({ !isForbidden($0) }) {
                result.append(character)
                lastWasSpace = false
            } else if !lastWasSpace {
                result.append(" ")
                lastWasSpace = true
            }
        }
        let trimmed = result.trimmingCharacters(in: .whitespaces)
        return trimmed.count > maxNoteLength ? String(trimmed.prefix(maxNoteLength)) : trimmed
    }

    static func isForbidden(_ scalar: Unicode.Scalar) -> Bool {
        switch scalar.properties.generalCategory {
        case .control, .format, .lineSeparator, .paragraphSeparator, .surrogate, .unassigned: return true
        default: return false
        }
    }

    /// Echoes rejected input without control characters, so error messages stay on one line.
    static func printable(_ text: String) -> String {
        let escaped = text.unicodeScalars.map { isForbidden($0) ? "\\u{\(String($0.value, radix: 16))}" : String($0) }.joined()
        return "'" + String(escaped.prefix(200)) + "'"
    }
}

/// One denial of the hardened preset with the reason it exists.
public struct PresetEntry: Sendable, Equatable, Hashable {
    public enum Kind: Sendable, Equatable, Hashable {
        case exec(String)
        case mach(String)
    }

    public var kind: Kind
    public var reason: String

    public init(_ kind: Kind, _ reason: String) {
        self.kind = kind
        self.reason = reason
    }
}

/// Opt-in denials for tools and services that let code act outside the sandbox or change the system.
///
/// Deliberately not denied: `security` and `defaults` (sv's `configure` uses them on every session start) and any
/// service TLS, DNS or the keychain need (`trustd`, `securityd`, `mDNSResponder`, `configd`, `ocspd`).
/// Verify on a real Mac before relying on it: service names differ between macOS releases.
public enum HardenedPreset {
    public static let entries: [PresetEntry] = [
        PresetEntry(.exec("/usr/bin/osascript"), "AppleScript/JXA can drive GUI apps of the logged-in session"),
        PresetEntry(.exec("/usr/bin/osacompile"), "builds AppleScript applets that run outside the sandbox when opened"),
        PresetEntry(.exec("/usr/bin/automator"), "runs Automator workflows, which script GUI apps like osascript"),
        PresetEntry(.exec("/usr/bin/shortcuts"), "runs Shortcuts, which execute in the Shortcuts service outside the sandbox"),
        PresetEntry(.exec("/usr/bin/open"), "asks LaunchServices to open apps, files and URLs in the logged-in session"),
        PresetEntry(.exec("/bin/launchctl"), "submits launchd jobs, which start without the sandbox-exec profile"),
        PresetEntry(.exec("/usr/sbin/screencapture"), "captures the screen of the logged-in session"),
        PresetEntry(.exec("/usr/bin/tccutil"), "resets privacy (TCC) decisions"),
        PresetEntry(.exec("/usr/sbin/networksetup"), "reconfigures interfaces, DNS and proxies"),
        PresetEntry(.exec("/usr/sbin/systemsetup"), "changes system settings (remote login, time, power)"),
        PresetEntry(.exec("/usr/bin/dscl"), "reads and edits accounts and groups in the directory service"),
        PresetEntry(.mach("com.apple.pasteboard.1"), "clipboard of the logged-in session (read secrets, plant commands)"),
        PresetEntry(.mach("com.apple.coreservices.launchservicesd"), "LaunchServices: opens apps, documents and URLs for the caller"),
        PresetEntry(.mach("com.apple.coreservices.appleevents"), "Apple Events to other apps (sv denies com.apple.appleeventsd)"),
    ]
}
